config/routes.rb
RorCloud::Application.routes.draw do
  resources :kp_files

  resources :users

  match '/connect', to: 'sessions#connect'
  match '/callback', to: 'sessions#callback'
  match '/download', to: 'sessions#download'
  match '/show', to: 'sessions#show'
  match '/view', to: 'sessions#view'

  get "static_pages/index"

end

app/models/kp_file.rb
class KpFile < ActiveRecord::Base
  attr_accessible :create_time, :file_id, :is_delete, :modify_time, :name, :rev, :sha1, :share_id, :size, :type
end

app/controllers/kp_files_controller.rb
class KpFilesController < ApplicationController
  # GET /kp_files
  # GET /kp_files.json
  def index
    @kp_files = KpFile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kp_files }
    end
  end

  # GET /kp_files/1
  # GET /kp_files/1.json
  def show
    @kp_file = KpFile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kp_file }
    end
  end

  # GET /kp_files/new
  # GET /kp_files/new.json
  def new
    @kp_file = KpFile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kp_file }
    end
  end

  # GET /kp_files/1/edit
  def edit
    @kp_file = KpFile.find(params[:id])
  end

  # POST /kp_files
  # POST /kp_files.json
  def create
    @kp_file = KpFile.new(params[:kp_file])

    respond_to do |format|
      if @kp_file.save
        format.html { redirect_to @kp_file, notice: 'Kp file was successfully created.' }
        format.json { render json: @kp_file, status: :created, location: @kp_file }
      else
        format.html { render action: "new" }
        format.json { render json: @kp_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kp_files/1
  # PUT /kp_files/1.json
  def update
    @kp_file = KpFile.find(params[:id])

    respond_to do |format|
      if @kp_file.update_attributes(params[:kp_file])
        format.html { redirect_to @kp_file, notice: 'Kp file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kp_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kp_files/1
  # DELETE /kp_files/1.json
  def destroy
    @kp_file = KpFile.find(params[:id])
    @kp_file.destroy

    respond_to do |format|
      format.html { redirect_to kp_files_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/kp_files_helper.rb
module KpFilesHelper
end

app/views/kp_files/_form.html.erb
<%= form_for(@kp_file) do |f| %>
  <% if @kp_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kp_file.errors.count, "error") %> prohibited this kp_file from being saved:</h2>

      <ul>
      <% @kp_file.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sha1 %><br />
    <%= f.text_field :sha1 %>
  </div>
  <div class="field">
    <%= f.label :is_delete %><br />
    <%= f.text_field :is_delete %>
  </div>
  <div class="field">
    <%= f.label :rev %><br />
    <%= f.number_field :rev %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :create_time %><br />
    <%= f.date_select :create_time %>
  </div>
  <div class="field">
    <%= f.label :modify_time %><br />
    <%= f.date_select :modify_time %>
  </div>
  <div class="field">
    <%= f.label :share_id %><br />
    <%= f.number_field :share_id %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.number_field :size %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :file_id %><br />
    <%= f.text_field :file_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kp_files/edit.html.erb
<h1>Editing kp_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @kp_file %> |
<%= link_to 'Back', kp_files_path %>

app/views/kp_files/index.html.erb
<h1>Listing kp_files</h1>

<table>
  <tr>
    <th>Sha1</th>
    <th>Is delete</th>
    <th>Rev</th>
    <th>Name</th>
    <th>Create time</th>
    <th>Modify time</th>
    <th>Share</th>
    <th>Size</th>
    <th>Type</th>
    <th>File</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kp_files.each do |kp_file| %>
  <tr>
    <td><%= kp_file.sha1 %></td>
    <td><%= kp_file.is_delete %></td>
    <td><%= kp_file.rev %></td>
    <td><%= kp_file.name %></td>
    <td><%= kp_file.create_time %></td>
    <td><%= kp_file.modify_time %></td>
    <td><%= kp_file.share_id %></td>
    <td><%= kp_file.size %></td>
    <td><%= kp_file.type %></td>
    <td><%= kp_file.file_id %></td>
    <td><%= link_to 'Show', kp_file %></td>
    <td><%= link_to 'Edit', edit_kp_file_path(kp_file) %></td>
    <td><%= link_to 'Destroy', kp_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kp file', new_kp_file_path %>

app/views/kp_files/new.html.erb
<h1>New kp_file</h1>

<%= render 'form' %>

<%= link_to 'Back', kp_files_path %>

app/views/kp_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sha1:</b>
  <%= @kp_file.sha1 %>
</p>

<p>
  <b>Is delete:</b>
  <%= @kp_file.is_delete %>
</p>

<p>
  <b>Rev:</b>
  <%= @kp_file.rev %>
</p>

<p>
  <b>Name:</b>
  <%= @kp_file.name %>
</p>

<p>
  <b>Create time:</b>
  <%= @kp_file.create_time %>
</p>

<p>
  <b>Modify time:</b>
  <%= @kp_file.modify_time %>
</p>

<p>
  <b>Share:</b>
  <%= @kp_file.share_id %>
</p>

<p>
  <b>Size:</b>
  <%= @kp_file.size %>
</p>

<p>
  <b>Type:</b>
  <%= @kp_file.type %>
</p>

<p>
  <b>File:</b>
  <%= @kp_file.file_id %>
</p>


<%= link_to 'Edit', edit_kp_file_path(@kp_file) %> |
<%= link_to 'Back', kp_files_path %>